language: ruby
rvm:
  - 3.0
  - 3.1
  - 3.2
  - 3.3
gemfile:
  - gemfiles/Gemfile.rails-7
  - gemfiles/Gemfile.rails-8
matrix:
  allow_failures:
    - rvm: 3.3 # Example for allowing experimental Ruby versions
before_install:
  - gem install bundler
script:
  - bundle exec rspec
cache: bundler
